FROM python:3.9

### If running on the host machine, we might have to install python there. And may be a different base image? ###
### RUN yum -y install python3
## RUN alias python=python3
## RUN sudo apt install python3-pip
## RUN pip3 install paho-mqtt python-etcd
## RUN pip3 install lupa
## RUN sudo apt-get install lua5.1

### Add own Entrypoint Script, and other scripts dedicated for each use case of the agent ###
COPY ./run.sh /run.sh
COPY ./python-scripts /python-scripts

RUN chmod +x /python-scripts/start-agent.py


EXPOSE 22

ENTRYPOINT ["sh", "/run.sh"]
